services:

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - public
      - internal

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - docker-local.env
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started
    networks:
      - public
      - internal

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - docker-local.env
    networks:
      - public
      - internal

  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    env_file:
      - docker-local.env
    networks:
      - internal
    expose:
      - "11434"

volumes:
  postgres_data:
  ollama_data:

networks:
  public:
    driver: bridge

  internal:
    driver: bridge
    internal: true